//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookIssueTable
    {
        public int IBID { get; set; }
        public int BookID { get; set; }
        public string EMP_EPFNo { get; set; }
        [Required(ErrorMessage = "Please Select Issue Date !")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime IssueDate { get; set; }
        [Required(ErrorMessage = "Please Select Return Date !")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime ReturnDate { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CollectDate { get; set; }
        public string Collectby { get; set; }
        public string Issueby { get; set; }
    
        public virtual BooksTable BooksTable { get; set; }
        public virtual EmployeeHRM EmployeeHRM { get; set; }
    }
}
