//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMPK_LMSEntities : DbContext
    {
        public CMPK_LMSEntities()
            : base("name=CMPK_LMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookIssueTable> BookIssueTables { get; set; }
        public virtual DbSet<BooksTable> BooksTables { get; set; }
        public virtual DbSet<BookTypesTable> BookTypesTables { get; set; }
        public virtual DbSet<EmployeeHRM> EmployeeHRMS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<UserTypesTable> UserTypesTables { get; set; }
        public virtual DbSet<AllissueBook> AllissueBooks { get; set; }
        public virtual DbSet<Booksview> Booksviews { get; set; }
        public virtual DbSet<Returned> Returneds { get; set; }
        public virtual DbSet<ReturnPending> ReturnPendings { get; set; }
    }
}
